name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'hosts-switch-linux-amd64'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'hosts-switch-windows-amd64'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'hosts-switch'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        #        uses: dAppServer/wails-build-action@v2.2
        uses: conkayyan/wails-build-action@v2.9.1
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.22.11'
          wails-version: 'v2.9.2'
          node-version: '22.5.1'
          deb-app: hosts-switch
          deb-app-name: "Hosts Switch"
